name: Deploy
on:
  push:
    branches:
      - source
    tags:
      - "!*"
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: LLK/scratch-gui
          ref: develop
      - run: npm install
      - uses: actions/checkout@v2
        with:
          path: ./stretch3
      - uses: actions/checkout@v2
        with:
          repository: bricklife/scratch-lego-bluetooth-extensions
          path: ./lego
      - uses: actions/checkout@v2
        with:
          repository: champierre/ml2scratch
          path: ./ml2scratch
      - uses: actions/checkout@v2
        with:
          repository: champierre/posenet2scratch
          path: ./posenet2scratch
      - uses: actions/checkout@v2
        with:
          repository: microbit-more/mbit-more-v2
          path: ./microbitMore
      - uses: actions/checkout@v2
        with:
          repository: champierre/tm2scratch
          path: ./tm2scratch
      - uses: actions/checkout@v2
        with:
          repository: champierre/tmpose2scratch
          path: ./tmpose2scratch
      - uses: actions/checkout@v2
        with:
          repository: tfabworks/xcx-g2s
          path: ./xcx-g2s
      - uses: actions/checkout@v2
        with:
          repository: champierre/scratch2maqueen
          path: ./scratch2maqueen
      - uses: actions/checkout@v2
        with:
          repository: champierre/handpose2scratch
          path: ./handpose2scratch
      - uses: actions/checkout@v2
        with:
          repository: champierre/facemesh2scratch
          path: ./facemesh2scratch
      - uses: actions/checkout@v2
        with:
          repository: con3office/pasorich
          path: ./pasorich
      - uses: actions/checkout@v2
        with:
          repository: sugiura-lab/scratch3-qrcode
          path: ./scratch3-qrcode
      - uses: actions/checkout@v2
        with:
          repository: champierre/speech2scratch
          path: ./speech2scratch
      - uses: actions/checkout@v2
        with:
          repository: champierre/ic2scratch
          path: ./ic2scratch
      - uses: actions/checkout@v2
        with:
          repository: NorifumiOgawa/iftttWebhooks
          path: ./iftttWebhooks
      - uses: actions/checkout@v2
        with:
          repository: con3office/numberbank
          path: ./numberbank
      - run: sh ./numberbank/install.sh
      - run: sh ./iftttWebhooks/install.sh
      - run: sh ./ic2scratch/install.sh
      - run: sh ./speech2scratch/install.sh
      - run: sh ./scratch3-qrcode/install.sh
      - run: sh ./stretch3/pasorich/install.sh
      - run: sh ./handpose2scratch/install.sh
      - run: sh ./facemesh2scratch/install.sh
      - run: sh ./scratch2maqueen/install.sh
      - run: sh ./xcx-g2s/scripts/stretch3-install.sh
      - run: sh ./tmpose2scratch/install.sh
      - run: sh ./tm2scratch/install.sh
      - run: sh ./microbitMore/install-stretch3.sh
      - run: sh ./posenet2scratch/install.sh
      - run: sh ./ml2scratch/install.sh
      - run: sh ./lego/scripts/install-duplotrain.sh
      - run: sh ./stretch3/add_ga_tracking_code.sh
      - run: npm run build
      - run: cp ./stretch3/index.html ./build/index.html
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
          publish_branch: master
